[project]
name = "eda-mid-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
    "isort>=9.0.1",
    "nbformat>=5.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "streamlit>=1.63.0",
]

[dependency-groups]
dev = [
    "black[jupyter]>=26.5.1",
]
